frontend:
  image: zhangrui20200722/frontend
  tag: 080116e
  autoscaling:
    averageUtilization: 90
backend:
  image: zhangrui20200722/backend
  tag: 080116e
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
